### ISSUE TITLE
Display the results in stdout by default

### ISSUE THREAD

**Issue by jhonis** [ChistaDATA/ChistaDATA-Anansi-Profiler#22]
**Is your feature request related to a problem? Please describe.**
Every time we run anansi executable, it sends the output to a file and then we have to open that file in order to see the results.

**Describe the solution you'd like**
It would be nice if the results were displayed in the standard output. There should be an option or argument to send the results to a file but that should not be the default behaviour.

**Describe alternatives you've considered**
NA

**Additional context**
For beginner users it's not intuitive to check the output of a command line tool in a file, this kind of tool usually displays its results in the standard output.

**Comment by vishal-joshy** [comment]
https://github.com/ChistaDATA/ChistaDATA-Anansi-Profiler/pull/30
