### ISSUE TITLE
[EPIC] UX design for Anansi-Profiler HTML report

### ISSUE THREAD

**Issue by jhonis** [ChistaDATA/ChistaDATA-Anansi-Profiler#38]
Design a simple, easy-to-use HTML report for database query analysis , showing key metrics and performance insights for efficient analysis.

### Work-in-progress UI
![Image](https://github.com/user-attachments/assets/90bfce5b-2b1c-4a18-a0f6-4bd14ec8dc39)

**Comment by vaisakhvm** [comment]
Let's close this ticket for now and create a new one if anything comes up.
